version: 2.1
orbs:
  gh: circleci/github-cli@1.0.3
  browser-tools: circleci/browser-tools@1.4.6
jobs:
    build:
        docker:
            - image: cimg/node:18.17.0-browsers
        resource_class: large
        steps:
            - checkout
            - browser-tools/install-browser-tools
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "package.json" }}-{{ checksum "./angular/components/package.json" }}-{{ checksum "./react/icons/package.json" }}-{{ checksum "./react-native/package.json" }}
                      - v2-dependencies-
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install
                      cd react/icons
                      yarn install
                      cd ../demo
                      yarn install
                      cd ../../angular/components
                      yarn install
                      cd ../demos/showcase
                      yarn install
                      cd ../../../react-native
                      yarn install
                      cd demo
                      yarn install
            - save_cache:
                  paths:
                      - node_modules
                      - react/icons/node_modules
                      - angular/components/node_modules
                      - react-native/node_modules
                  key: v2-dependencies-{{ checksum "package.json" }}-{{ checksum "./angular/components/package.json" }}-{{ checksum "./react/icons/package.json" }}-{{ checksum "./react-native/package.json" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
            - run:
                  name: Lint
                  command: |
                      yarn lint
            - run:
                  name: Build All Packages
                  command: |
                      yarn build:all
            - run:
                  name: Test All Functions
                  command: |
                      yarn test:functions
                      cd ..
            - run:
                  name: Test All Demos
                  command: |
                      yarn test:demos
                      cd ..
            - persist_to_workspace:
                  root: .
                  paths:
                    - angular/dist
                    - react/icons/dist
                    - react-native/dist

    publish:
      docker:
        - image: cimg/node:18.17.0-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command:  |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @brightlayer-ui/ng-progress-icons
            command: cd angular/components && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @brightlayer-ui/react-progress-icons
            command: cd react/icons && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @brightlayer-ui/react-native-progress-icons
            command: cd react-native && yarn publish:package -b $CIRCLE_BRANCH

workflows:
  version: 2
  icons:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
