#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

yarn_major="$(yarn --version | cut -d. -f1)"
if [[ "$yarn_major" -ge 2 ]]; then
  yarn install --immutable
else
  yarn install --frozen-lockfile
fi

yarn prettier:check
yarn lint